version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: swift
    directory: /app
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directories:
      - /db
      - /builder/universal
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
