//! German/English country names -> ISO 3166-1 alpha-2 for place search
//! ("Kroatien" / "Croatia" / "Hrvatska" -> HR). Places store only `cc`,
//! so text queries for countries are resolved here, not in SQL.

pub fn country_code(query: &str) -> Option<&'static str> {
    let q = query.trim().to_lowercase();
    NAMES.iter().find(|(n, _)| *n == q).map(|(_, c)| *c)
}

static NAMES: &[(&str, &str)] = &[
    // Europe
    ("deutschland", "DE"), ("germany", "DE"),
    ("kroatien", "HR"), ("croatia", "HR"), ("hrvatska", "HR"),
    ("frankreich", "FR"), ("france", "FR"),
    ("italien", "IT"), ("italy", "IT"), ("italia", "IT"),
    ("spanien", "ES"), ("spain", "ES"), ("espana", "ES"),
    ("portugal", "PT"),
    ("oesterreich", "AT"), ("österreich", "AT"), ("austria", "AT"),
    ("schweiz", "CH"), ("switzerland", "CH"),
    ("niederlande", "NL"), ("netherlands", "NL"), ("holland", "NL"),
    ("belgien", "BE"), ("belgium", "BE"),
    ("luxemburg", "LU"), ("luxembourg", "LU"),
    ("daenemark", "DK"), ("dänemark", "DK"), ("denmark", "DK"),
    ("schweden", "SE"), ("sweden", "SE"),
    ("norwegen", "NO"), ("norway", "NO"),
    ("finnland", "FI"), ("finland", "FI"),
    ("island", "IS"), ("iceland", "IS"),
    ("irland", "IE"), ("ireland", "IE"),
    ("grossbritannien", "GB"), ("großbritannien", "GB"), ("england", "GB"),
    ("united kingdom", "GB"), ("uk", "GB"), ("schottland", "GB"), ("scotland", "GB"),
    ("polen", "PL"), ("poland", "PL"),
    ("tschechien", "CZ"), ("czechia", "CZ"), ("czech republic", "CZ"),
    ("slowakei", "SK"), ("slovakia", "SK"),
    ("ungarn", "HU"), ("hungary", "HU"),
    ("slowenien", "SI"), ("slovenia", "SI"),
    ("bosnien", "BA"), ("bosnien und herzegowina", "BA"), ("bosnia", "BA"),
    ("serbien", "RS"), ("serbia", "RS"),
    ("montenegro", "ME"),
    ("albanien", "AL"), ("albania", "AL"),
    ("nordmazedonien", "MK"), ("mazedonien", "MK"), ("north macedonia", "MK"),
    ("griechenland", "GR"), ("greece", "GR"),
    ("bulgarien", "BG"), ("bulgaria", "BG"),
    ("rumaenien", "RO"), ("rumänien", "RO"), ("romania", "RO"),
    ("moldau", "MD"), ("moldova", "MD"),
    ("ukraine", "UA"),
    ("belarus", "BY"), ("weissrussland", "BY"), ("weißrussland", "BY"),
    ("russland", "RU"), ("russia", "RU"),
    ("estland", "EE"), ("estonia", "EE"),
    ("lettland", "LV"), ("latvia", "LV"),
    ("litauen", "LT"), ("lithuania", "LT"),
    ("malta", "MT"),
    ("zypern", "CY"), ("cyprus", "CY"),
    ("tuerkei", "TR"), ("türkei", "TR"), ("turkey", "TR"), ("tuerkiye", "TR"),
    ("monaco", "MC"), ("liechtenstein", "LI"), ("andorra", "AD"), ("san marino", "SM"),
    // Americas
    ("usa", "US"), ("vereinigte staaten", "US"), ("united states", "US"), ("amerika", "US"),
    ("kanada", "CA"), ("canada", "CA"),
    ("mexiko", "MX"), ("mexico", "MX"),
    ("brasilien", "BR"), ("brazil", "BR"),
    ("argentinien", "AR"), ("argentina", "AR"),
    ("chile", "CL"), ("peru", "PE"), ("kolumbien", "CO"), ("colombia", "CO"),
    ("kuba", "CU"), ("cuba", "CU"),
    ("dominikanische republik", "DO"), ("dominican republic", "DO"),
    ("costa rica", "CR"), ("panama", "PA"),
    // Asia / Oceania
    ("japan", "JP"), ("china", "CN"), ("suedkorea", "KR"), ("südkorea", "KR"),
    ("south korea", "KR"), ("korea", "KR"),
    ("indien", "IN"), ("india", "IN"),
    ("thailand", "TH"), ("vietnam", "VN"), ("indonesien", "ID"), ("indonesia", "ID"),
    ("bali", "ID"), ("malaysia", "MY"), ("singapur", "SG"), ("singapore", "SG"),
    ("philippinen", "PH"), ("philippines", "PH"),
    ("sri lanka", "LK"), ("nepal", "NP"), ("malediven", "MV"), ("maldives", "MV"),
    ("vereinigte arabische emirate", "AE"), ("uae", "AE"), ("dubai", "AE"),
    ("katar", "QA"), ("qatar", "QA"),
    ("israel", "IL"), ("jordanien", "JO"), ("jordan", "JO"),
    ("saudi-arabien", "SA"), ("saudi arabia", "SA"),
    ("georgien", "GE"), ("georgia", "GE"), ("armenien", "AM"), ("armenia", "AM"),
    ("aserbaidschan", "AZ"), ("azerbaijan", "AZ"), ("kasachstan", "KZ"), ("kazakhstan", "KZ"),
    ("australien", "AU"), ("australia", "AU"),
    ("neuseeland", "NZ"), ("new zealand", "NZ"),
    // Africa
    ("aegypten", "EG"), ("ägypten", "EG"), ("egypt", "EG"),
    ("marokko", "MA"), ("morocco", "MA"),
    ("tunesien", "TN"), ("tunisia", "TN"),
    ("suedafrika", "ZA"), ("südafrika", "ZA"), ("south africa", "ZA"),
    ("kenia", "KE"), ("kenya", "KE"), ("tansania", "TZ"), ("tanzania", "TZ"),
    ("namibia", "NA"), ("kap verde", "CV"), ("cape verde", "CV"),
    ("mauritius", "MU"), ("seychellen", "SC"), ("seychelles", "SC"),
];
